### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by frixdk** [aau-claaudia/OpenStackGateway#13]
If a database is needed for whatever reason to save meta data for jobs or similar it should be implemented like in this example:
https://spring.io/guides/tutorials/spring-boot-kotlin/

Liquibase should be used to handle database migrations. Take a look at the prototype implementation here: https://github.com/aau-claaudia/OpenStackGateway_old/commit/72a66fb0abd3864e965d0f1a4caba750370ba039

Migrations should be stored in:

src/main/resources/db/changelog/changes/01-Initial.yaml

and be referenced in src/main/resources/db/changelog/db.changelog-master.yaml :

```
databaseChangeLog:
  - include:
      file: db/changelog/changes/01-Initial.yaml
```

The database should be the inclued H2 for local testing and postgress for production

```
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/openstackgateway
    username: username
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none 
```

A dockerfile could be included to make it easier for developers to spin up a local postgress db

docker-compose.yml:
```
version: '2.2'
services:
  postgres01:
    image: postgres
    container_name: postgres01
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openstackgateway
```
